project:
  type: website
  output-dir: docs

website:
  title: "temp_website"
  page-footer:
    left: |
      &copy; Arlo Heitler, 2024<br>
      All content licensed under <i class='bi-badge-cc'></i>
      [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)
    right: |
      Site built with <a href='https://quarto.org/'>Quarto</a>
  navbar:
    left:
      - href: index.qmd
        text: Home
        
      - about.qmd
      
      - href: Athletics.qmd
        text: Athletics
        
      - href: Projects.qmd
        text: Projects

format:
  html:
    theme: lux
    css: lux.css
    toc: true

editor: visual


